apiVersion: v1
kind: Secret
metadata:
    name: speedtest-app-key
    namespace: speedtest
type: Opaque
stringData:
    APP_KEY: ENC[AES256_GCM,data:j32eYA1sQRGEwJFpn6sEs1KwYT336bfATxV40780P1vxJoK8dv9wHt+I/U3FqdwvllEo,iv:SKsIwC4VMDPW5nL8cN3/Ngp3shA122vtgMc04+bUCg4=,tag:SbgS6rBniMhJNZybKWDGqg==,type:str]
sops:
    age:
        - recipient: age19z2tpqznrufggyewdz2pa8a7ftuscn9f28l0hxh28zzq2y4cfudquxkm7l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cUFMNUNaVUExV0hDK01h
            OXlNOWdGSk5IUEIwQzhQWGhYRUFldjJmbUNNCnFKM0VnNzdhYjF2cHU1WHJqYXRz
            d0FzUVpOVm5vSWpvNC9vQ2RWYnRUeTQKLS0tIGVudkNDYkVWNnhYRUYwaHpqMVdM
            TE5nZUIvellUS1ArQVBOK1NyMWpZRlUKQBQEMbw0zkwi+Qf0kuVAW9Df0YcBHtpH
            IH3B+O0NgG8T5sTklugTKGlQJZo4uabE9gL2mx9/74yXIlHD0YWmgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T20:13:28Z"
    mac: ENC[AES256_GCM,data:lfGENzEbm8rNKumWqkd8qAoBi60Yh2MLN/0eh/Ek0z0YUkB6Ol0lXbyj9vT8ID226V43OHRfvXcJZt/x5UDAYj/ywJBslTF8+ZGgArWxeh9NQZdh1yIF8tbIinNaqJbG3IBSCkLkkU6Hs3CcYQvvlHJ2HACQ5f7ATtu5gR5U+7I=,iv:tI/HWGqqB8H/uSNraC2pRQB/9SYKtbkNj8/Y2daXMy8=,tag:7+SbeWYD4jz9gsuaA78fvw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
