apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  failurePolicy: reinstall
  valuesContent: |-
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.lab`)
        entryPoints:
          - web
          - websecure
        tls:
          secretName: traefik-dashboard-tls
    metrics:
      prometheus:
        service:
          enabled: true
        serviceMonitor:
          enabled: true
