- name: Disable zram swap
  ansible.builtin.systemd:
    name: systemd-zram-setup@zram0.service
    state: stopped
    enabled: false
    masked: true
  register: swap_result

- name: Enable cgroups
  ansible.builtin.lineinfile:
    path: /boot/firmware/cmdline.txt
    regexp: '^((?!.*{{ item }}).+)$'
    line: '\1 {{ item }}'
    backrefs: true
  loop:
    - cgroup_enable=cpuset
    - cgroup_enable=memory
    - cgroup_memory=1
  register: cgroups_result

- name: Reboot
  ansible.builtin.reboot:
  when: swap_result.changed or cgroups_result.changed
